name: glados

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  schedule:
    - cron: "30 16 * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./glados/requirements.txt
      - name: Run checkin
        run: |
          python3 ./glados/glados.py '${{ secrets.GLADOS_COOKIE }}'
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@master  
